baseURL = "https://biodxandi.com"
languageCode = "es-mx"
title = "Dxandi"
# themesDir = "themes"
# theme = "hugo-serif-theme"
publishDir = "docs"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_call_box = true

  [params.logo]
    mobile = "images/logo-mobile.svg"
    desktop = "images/logo-mobile.svg"
    desktop_height = "60px"
    alt = "Dxandi"

  [params.homepage_meta_tags]
    meta_description = "Dxandi"
    meta_og_title = "Dxandi"
    meta_og_type = "website"
    meta_og_url = "pending"
    meta_og_image = "https://biodxandi.com"
    meta_og_description = "Dxandi"
    meta_twitter_card = "summary"
    meta_twitter_site = "@peps333"
    meta_twitter_creator = "@peps333"

  [params.footer]
    copyright_text = 'Powered by <a class="zerostatic" href="https://github.com/zerostaticthemes/hugo-serif-theme">Hugo Serif</a> theme for <a href="https://gohugo.io/">Hugo</a>.'

[menu]
  # Main Menu
  [[menu.main]]
    name = "Servicios"
    url = "/services/"
      weight = 1

  [[menu.main]]
      name = "Equipo"
      url = "/team/"
      weight = 2

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Contacto"
    url = "/contact/"
      weight = 2
